Remove duplicated code, improve flow
LPGhatguy/roblox-lua-promise pull request #5
Opened 2018-07-07 06:37 UTC by Validark

- The `pack` function was previously rewritten 4 times, changed to 0
- Made it more obvious that `_queuedResolve` and `_queuedReject` are arrays of functions
- Instead of explicitly returning void when the status isn't `Started` in functions `_resolve` and `_reject`, do so implicitly
	- This makes it more obvious (to me) what exactly the conditions are for having the code run. It is also more expandable in the future for what should happen if the status is something else

- All functionality should be **exactly** the same

2018-07-21 19:24 UTC, LPGhatguy requested changes

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +	-- This is useful for debugging issues within the Promise implementation itself.
Comments are wrapped to 80 columns wide on purpose, which is why this looked kind of strange.

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +			self._queuedReject[#self._queuedReject + 1] = failureCallback
I don't think this change adds any clarity, and the performance difference is negligible.

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +		-- Queues representing functions we should invoke when we update! (arrays of functions)
The way to describe what the type would probably be to change the comment to:

```lua
-- Lists of functions to invoke when our status updates
```

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +	if self._status == Promise.Status.Started then
Early return here reduced rightward drift substantially. Unless we have substantial code that happens in the else-branch, I've favored early-return style for awhile.

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +		local numRejectionHandlers = #self._queuedReject
This is a lot clearer. Whatever I was trying to do with `isEmpty` seems silly.

2018-07-21 19:24 UTC, LPGhatguy commented on lib/init.lua
> +	return select("#", ...), { ... }
Nice, this is a nifty change.

2018-07-21 20:23 UTC, Validark commented
Updated. Please review again!

2018-09-14 20:51 UTC, LPGhatguy commented
Sorry for the long pause on this!

After I merged @evaera's implementation of `Promise.all`, I decided to pick and choose a few things from your PRs. They fix a lot of really really nice things, but also change a few things that I don't think need to be changed.

Take a look at this commit range and let me know if there's anything missing you think is really important: https://github.com/LPGhatguy/roblox-lua-promise/compare/3c9881a478de552445b31916952caa0914360b07...9bda3e68ea927afa2709df7a969af3c06599e5e1

In the future, smaller pull requests would definitely help me merge in formatting fixes like this more easily! I'm going to go ahead and close this one for now.

2018-09-14 20:51 UTC, closed without merging